###
env: "dev"
logDir: "/tmp"
address: "0.0.0.0:8123"

hotwalletPriv1: ""
hotwalletAddress1: ""

hotwalletPriv2: ""
hotwalletAddress2: ""

hotwalletFeePriv1: ""
hotwalletFeeAddress1: ""

hotwalletFeePriv2: ""
hotwalletFeeAddress2: ""

hotwalletFeePriv3: ""
hotwalletFeeAddress3: ""

minHotWallet2Amount: ""
maxTranferAmount: ""

database:
  host: "34.143.195.7"
  port: "3306"
  user: "root"
  password: "M#p+ci2FO2+%di#p92D#!p9"
  name: "fe-dev"