###
env: "dev"
logDir: "/tmp"
database:
  host: ""
  port: ""
  user: ""
  password: ""
  name: ""
endpoints:
  filter: ""
network: ""
bitcoin:
  sender: ""
  senderprivatekey: ""
chainpool:
  senderprivatekey: ""
ton:
  words: ""
  password: ""